language: php
cache: composer

php:
  - '7.0'
  - '7.1'

before_script:
  - composer install --dev --prefer-source --no-interaction
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE `oshop`;'
  - php artisan migrate

script: phpunit

services:
  - mysql